"""empty message

Revision ID: 8134ddacbf4b
Revises: edd0aa65d409
Create Date: 2025-04-09 22:30:42.055821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8134ddacbf4b'
down_revision = 'edd0aa65d409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adress', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('adress')

    # ### end Alembic commands ###
