version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - ../../src/frontend:/workspaces/guidev-portfolio/frontend
      - ../../src/backend:/workspaces/guidev-portfolio/backend
    working_dir: /workspaces/guidev-portfolio
    ports:
      - "3000:3000" # Astro
      - "5431:5432" # Flask
    depends_on:
      - db
    environment:
      POSTGRES_USER: gitpod
      POSTGRES_DB: example
      POSTGRES_PASSWORD: postgres
    command: >
      bash -c "
        cd backend && flask run --host=0.0.0.0 & 
        cd ../frontend && npm install && npm run dev
      "

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: gitpod
      POSTGRES_DB: example
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
